[fix/aut780] FIAMS_FullScan_Unknown_test.exe assertion failure
dmccloskey/SmartPeak2 pull request #348
Opened 2021-03-31 15:42 UTC by ChristopherAbram

Seems like for some reason `f1->getIntensity()` and `f1->getMetaValue("peak_apex_int")` return an empty value, even though corresponding metadata are set in XML file. Also, `fm1.size()` returns 1225 and file contains `3161` features.
The code `(double)f1->getMetaValue("peak_apex_int")` causes following exception:
```bash
---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler: 
exception of type ConversionError occurred in line 478, function OpenMS::DataValue::operator double() const of /home/krzysztof/Workspace/OpenMS/src/openms/source/DATASTRUCTURES/DataValue.cpp
error message: Could not convert DataValue::EMPTY to double
---------------------------------------------------
```

The behaviour for f2 is correct for all cases.

📌 [WIP]: I need some input from the team on this issue.

2021-03-31 20:45 UTC, dmccloskey requested changes
Can investigate further why the generated and "test" featureMap are no longer the same?  I would recommend starting with where they are divergent by printing out the names of the features and seeing where the discrepencies begin.

2021-03-31 20:45 UTC, dmccloskey commented on src/examples/source/FIAMS_FullScan_Unknown_test.cpp
> +  // assert(Utilities::assert_close((double)f1->getMetaValue("peak_apex_int"), 3.5241834375e05));
Is this value empty?  It should not be.

2021-03-31 20:45 UTC, dmccloskey commented on src/examples/source/FIAMS_FullScan_Unknown_test.cpp
> -  assert(fm1.size() == fm2.size());
This is a problem.  The two sizes should be equal.

2021-03-31 20:45 UTC, dmccloskey commented on src/examples/source/FIAMS_FullScan_Unknown_test.cpp
> +  // assert(Utilities::assert_close((double)f1->getIntensity(), (double)f2->getIntensity()));
These values should be equal.

2021-04-13 12:08 UTC, ChristopherAbram commented on src/examples/source/FIAMS_FullScan_Unknown_test.cpp
> +    const auto& f2 = fm2[0].getSubordinates()[0];
`getSubordinates()` is required to read correct values of meta data such as `peak_apex_int`.
I was inspired by this: https://github.com/OpenMS/OpenMS/blob/d9692da0d410c06b6cdc960f608a5c962360d09c/src/tests/class_tests/openms/source/MRMFeatureSelector_test.cpp#L97

2021-04-13 13:55 UTC, dmccloskey reviewed
Thanks for making the updates.

2021-04-13 13:55 UTC, dmccloskey approved these changes

2021-04-13 13:55 UTC, merged